version: '3.8'

# When connecting to OneBot v11 Napcat, please use this compose file for one-click deployment: https://github.com/NapNeko/NapCat-Docker/blob/main/compose/astrbot.yml

services:
  astrbot:
    image: soulter/astrbot:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    expose:
      - "6185"
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - astrbot_data:/AstrBot/data
      - /etc/localtime:/etc/localtime:ro

volumes:
  astrbot_data:
